//
//  BikeModel.swift
//  MVVMPatrones
//
//  Created by Pedro on 3/10/23.
//

import Foundation

typealias BikesModel = [BikeModel]

//STRUCT
struct BikeModel {
    var name: String
    var imageName: String?
    var imageURL: String?
    var description: String
}

//NUESTROS DATOS
var sampleBikeData: BikesModel = [
    BikeModel(name: "Bagger",
                   imageName: "bagger_bike",
                   imageURL: "https://i.pinimg.com/736x/e6/04/f6/e604f6aab78d2be8e1db81f3ae8f78ca--custom-baggers-classic-bikes.jpg",
                   description: "Moda que aparece en los años 60 tanto en América como Reino Unido que se caracteriza por vestir a la moto con grandes maletas y guardabarros hasta casi llegar al suelo. Hoy día se exageran con grandes llantas delanteras, incluso de 30 pulgadas con colores brillantes y un nivel artístico en sus grafismos bastante elevado. En el caso de las motos custom Bagger, la característica predominante serían los accesorios y su utilidad, como verán más adelante. Estos accesorios, además de útiles, les aportan gran belleza estética, otro valor agregado a este tipo de personalizaciones. Algunos de ellos bastantes llamativos, sobre todo en los desfiles de motos clásicas. De ahí a que también se les conozca como Dresser del inglés to dress (vestir).Sus nombres vienen derivados de las bolsas (Bags) que comenzaron a colocar a ambos costados de la moto. Además de otros accesorios como las borlas de los manubrios, y las piezas de cuero por cualquier parte de la moto y elementos cromados. Por lo general, estas personalizaciones son menos agresivas con la moto en cuestión, ya que no afectan a la potencia, estructura o maniobrabilidad."),
    BikeModel(name: "Bobber",
                   imageName: "bobber_bike",
                   imageURL: "https://www.thunderbike.com/wp-content/uploads/2021/10/4k-Black-Slim_Thunderbike_Glatzzo-Michael-Rauscher5_BEITRAG-545x364.jpg",
                   description: "Estilo de moto que aparece en los años 40. Se crean a partir de motocicletas de marcas como Harley Davidson, Indian o Triumph. Se caracterizan por ser motos bajas y largas, con el mismo diámetro y grosor de rueda delantera y trasera. Sus neumáticos imitan el viejo estilo y sus llantas suelen ser de radios clásicos. Todo lo superficial se desmonta, incluso el guardabarros delantero. Se simplifican los tubos de escape y se les envuelven en cinta anti calórica. (Aunque esto os lo podéis encontrar en otros estilos de moto). El estilo Bobber se caracteriza en primer lugar por desprender a la moto de cualquier exceso de carrocería, sobre todo al eliminar el guardabarros delantero y reducir el trasero. Algunas de sus características más habituales son los guardapolvos en la suspensión delantera, la utilización de gruesos neumáticos del mismo tamaño en las dos ruedas (muy habituales con banda blanca), asiento de muelles monoplaza, sustitución de piezas cromadas por otras pintadas, como las llantas o partes del motor y pintura mate tanto para el depósito como para los guardabarros, etc. También podemos apreciar detalles muy compartidos en este tipo de transformaciones como depósitos de gasolina más pequeños y tubos de escape acortados. Debido a su estilo clásico, para este tipo de transformaciones se suelen utilizar motores clásicos, aunque se puede ver motocicletas Bobber realizadas con motores más actuales. Este estilo es muy peculiar y sin duda sigue influyendo a las marcas a la hora de diseñar sus nuevas motocicletas como Harley Davidson, Triumph y Honda por poner algunos ejemplos."),
    BikeModel(name: "Brat Style",
                   imageName: "brat_style",
                   imageURL: "https://1.bp.blogspot.com/-vmQgR9PJU4M/WEZEHiR_brI/AAAAAAAAEXw/j_tAtlzXMH4ipMeWTAm7IC3FG1sFedy_gCLcB/s1600/custom-bmw-motorcycle-625x417.jpg",
                   description: "Algunos lo confunden e incluso lo llaman Cafe Racer pero dista mucho de serlo. Fundamentalmente se usan como base motos japonesas de cilindrada media tipo Yamaha SR, Honda CB o Kawasaki KZ. Consiste al igual que el estilo Bobber en dejar la moto en lo más básico, motor, depósito, asiento mínimo, ruedas, faro y lo necesario para rodar. Las características más distintivas son las llantas de estilo antiguo y el faro y luces mínimas. Son motos que han sido modificadas, como las motos custom, y contemplan estructuras híbridas entre elementos vintage, y personalización de los componentes modernos. Este movimiento se originó en Japón y actualmente esta manifestación motera se encuentra esparcida por todas partes gracias al auge que ha experimentado en la última década. El nombre de esta manifestación o movimiento motorista, se debe al término inglés “brat” que, traducido, se interpreta como “niño malcriado” que viene a significar el estilo de la moto de rebeldía y el espíritu motero desafiante de una época."),
    BikeModel(name: "Cafe Racer",
                   imageName: "cafe_racer",
                   imageURL: "https://caferacerpasion.com/wp-content/uploads/2014/12/honda-cb750-seven-fifty-spitfire09-macco-motors-1.jpg",
                   description: "Un estilo popularizado en el Reino Unido durante los años 50, principalmente por los rockers que personalizaban sus motos con pequeños carenados, modificaciones en chasis, estriberas, tubos de escape, colines y aligeramiento en general de la moto, quitando todo aquello que no fuera necesario, buscando siempre conseguir mayor velocidad y agilidad. La definición es sencilla, una Cafe Racer es una moto de los años cincuenta, producto de la cultura rocker del momento, época en la que se buscaban motos rápidas para ir en “peregrinación” de café en café. Su equivalente norteamericano sería una Bobber o una Chopper. El nombre, aunque esto es algo que pertenece a la leyenda urbana, parece que nació al unir esas cafeterías con las carreras que desarrollaban los jóvenes entre cada café y que duraban lo que una canción en la gramola del local. Concretando la definición un paso más, las Cafe Racer no eran más que motos normales que los propietarios transformaban para mejorar sus prestaciones y su manejo. Transformaciones que se centraban en estas mejoras pero que solían olvidar aspectos como la comodidad. De esta manera se instalaban manillares deportivos (estrechos y planos o incluso semi-manillares más deportivos) depósitos de mayor capacidad, asientos individuales y estriberas retrasadas para adaptar la posición del piloto y hacerla lo más aerodinámica posible. Todo lo demás se consideraba superfluo y por tanto se eliminaba de la moto sin contemplaciones."),
    BikeModel(name: "Chopper",
                   imageName: "chopper_bike",
                   imageURL: "https://i.pinimg.com/originals/1e/58/58/1e5858d899f2fd15b4f50f6ce40f4272.jpg",
                   description: "Del verbo inglés “to chop”[cortar] ya que se corta todo lo superfluo. Aparece la moda a finales de los 60 en EEUU y su característica principal es que son motos delgadas, bajas de atrás y altas por delante, con horquillas muy largas rozando lo esperpéntico. Los manillares de origen también se sustituyen por “cuelgamonos” que mantienen los brazos en alto, dando la impresión de que el piloto va colgado de ellos. La pintura es colorista y llamativa con gran presencia de aerografía. Una Chopper es un tipo de motocicleta modificada (Chopped), para tener un ángulo de lanzamiento mayor, con horquilla más larga, lo que le da una batalla y avance más grandes que el resto de los tipos de motocicletas. Normalmente tiene un manillar más largo a lo alto, lo que le da una posición a las manos más alta que los hombros del piloto. Puede estar basada en una motocicleta de producción o ser creada desde cero. Con respecto a las motocicletas tradicionales, las Chopper suelen ser más livianas, tienen tanques de combustible más pequeños, y sus parabrisas, luces, guardabarros y asientos son más pequeños o directamente fueron quitados."),
    BikeModel(name: "Rat Bike",
                   imageName: "rat_bike",
                   imageURL: "https://i.pinimg.com/originals/e0/96/d9/e096d95e7950f58b863ccb581f8c8fb9.jpg",
                   description: "Motos de aspecto desaliñado, donde predominan las piezas oxidadas o con falta de cualquier tipo de mantenimiento. Tienen un aspecto “viejuno” y cualquier pieza o accesorio, aunque no sea de esa moto, vale si tiene su correspondiente oxido. En definitiva sus creadores buscan que la moto funcione correctamente pero con un aspecto decadente, sucio y viejo. Suelen parecer motos como salidas de la película Mad Max. Incluso Brad Pitt se ha apuntado a esta moda comprándose para su colección una Rat Bike. Una Rat Bike nace cuando esa moto que tenemos empieza a envejecer y a necesitar piezas de recambio. Aquí es cuando comienza el proceso. El objetivo es no gastarse ni un solo duro y aprovechar cualquier otra cosa para sustituir las piezas que necesitemos, como si es algo que encontramos en la basura, eso sería mejor aún. El objetivo es mantener la moto en las condiciones mínimas y necesarias de usabilidad, sin preocuparse lo más mínimo por su apariencia o aspecto estético ¿A quién le importa eso? Aquí lo fundamental es que nuestra moto se mantenga lo suficientemente en forma como para rodar el máximo periodo de tiempo posible, y no se le pide más. No te preocupes por la pintura, no hay nada que no solucione un spray de pintura de color negro mate, en cualquier momento le das un repasito y listo. Latas para filtros de aire, trozos de neumáticos viejos para guardabarros, bidones que hacen de depósitos, cualquier cosa mullida hace de asiento si lo necesitamos, botes de plástico, cables, latas, tubos… el límite lo pone tu imaginación, y tu habilidad con la cinta americana, el alambre y los alicates."),
    BikeModel(name: "Street Fighter",
                   imageName: "street_fighter",
                   imageURL: "https://solomoto.es/wp-content/uploads/2019/06/ducati-v4-streetfighter.jpg",
                   description: "Estilo que hace algunos años hacía furor llegando a agotar algunos modelos de motos de segunda mano que servían de base para desarrollar este estilo. Podíamos traducirlo del inglés como “guerra urbana” Estas motos se diferencian de todas las demás custom en que la base sobre las que se desarrollan son motos deportivas japonesas o italianas. Se caracterizan estéticamente por tener un colín trasero alzado, formando un ángulo en ocasiones exagerado. Las Street Fighter tiene el puño americano como símbolo a modo de logotipo. Una Streetfighter es una motocicleta tipo bicicleta con motor. Originalmente puede ser naked de fábrica de alta potencia (hay controversia), o de tipo deportiva o superbike, a la que se le han eliminado los carenados y se ha modificado para darle una imagen y aspecto característicos. Generalmente también se le ha realizado una preparación al motor para dar un desempeño superior al de la motocicleta base. Originalmente las Streetfighters, son resultado de la evolución que experimentaron las motos más potentes de los 1980s y 1990s, para acabar consolidándose a principios del nuevo siglo como uno de los movimientos moteros con más proyección. A lo largo de los años y con asombrosa rapidez, el concepto ha ido radicalizándose, haciendo cada vez más extremas las preparaciones de Streetfighters. La base de una Streetfighter es una superbike o naked, que normalmente proviene de un siniestro o que presenta un deterioro general, que se personaliza mediante la eliminación del carenado (si lo tuviera) dejando el chasis y motor, a la que se le han efectuado otros cambios que le dan un aspecto más agresivo y que la diferencia de la moto de origen. Popularizada por los moteros de Europa, este tipo de motocicleta está ganando adeptos en todo el mundo siendo cada vez mayor la expansión de este movimiento.")
   
]

